### ISSUE TITLE
Any updates to this project

### ISSUE THREAD

**Issue by vijaysar** [tkach/FileProviderSample#1]
Hello Alex,

Looks like you started this for enumerating a client/server filesystem synchronization?  Did you make nay progress or is this abandoned?  Let me know I am looking for some project like this for connecting an ios app to a webdav server.

Thanks
Vijay

**Comment by tkach** [comment]
Hello @vijaysar i did this just to experiment with file provider extension, this is more just a template, I haven’t implemented client/server sync mechanism.
Looks like there’s a lot of great tutorials on the internet, such as Ray Wenderlich’s https://www.raywenderlich.com/697468-ios-file-provider-extension-tutorial, hope this will be useful for you.

**Comment by vijaysar** [comment]
Alex,

I have looked at that example.  It is helpful but want to avoid Heroku or a third party cloud dependency. Anyway thanks for reaching out timely!

Regards
Vijay
